# Generated by Django 3.2 on 2021-04-27 09:11

from django.db import migrations, models
import sharing.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='model',
            field=models.FileField(upload_to=sharing.models.handle_upload_to),
        ),
    ]
